### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by prmtl** [contextio/Python-ContextIO#11]
Hello,

I wanted to use contextio python lib in my project but unfortunately it is not available on PyPI. Is it possible to publish it on PyPI? 

I also saw that the name of the package in `setup.py` is "ContextIO-v2.0-Client-Library". Is there a reason it is not simply a "contextio"? 

Thanks!

**Comment by sushithegreat** [comment]
I've got the initial "official" release on PyPI here:

https://pypi.python.org/pypi/contextio
