### ISSUE TITLE
Can't use post_account

### ISSUE THREAD

**Issue by Lechucico** [contextio/Python-ContextIO#73]
That's the code:
```
api = c.ContextIO(
    consumer_key=CONSUMER_KEY,
    consumer_secret=CONSUMER_SECRET,
    api_version="lite",
    debug=True
)

accounts = api.post_account(email="test.living-digital@gmail.com")
```

Error: 
`Traceback (most recent call last):
  File "C:\Users\Albert\Desktop\context.io\users.py", line 22, in <module>
    accounts = api.post_account(email="test.living-digital@gmail.com")
AttributeError: 'Lite' object has no attribute 'post_account'
[<contextio.lib.resources.user.User object at 0x03C8AE90>]`

**Comment by sushithegreat** [comment]
The correct method to use in Lite is `post_user`.
